"""
Batch Simulation Data — 50 pre-seeded dispute scenarios for Track 03 demo.
Covers Visa, Mastercard, RuPay across 5 merchant categories.
"""

BATCH_SCENARIOS = [
    # --- STRONG WINS (should auto_submit) ---
    {"reason_code":"visa_10.4","network":"visa","has_3ds_auth":1,"has_delivery_proof":1,"has_avs_cvv_match":1,"has_ip_device_fingerprint":1,"has_prior_comms":0,"has_signed_receipt":0,"has_usage_logs":0,"days_remaining":14,"days_since_transaction":15,"repeat_dispute_count":0,"transaction_amount_inr":4500.0,"merchant_category":"ecommerce","merchant_current_dispute_ratio":0.005},
    {"reason_code":"visa_13.1","network":"visa","has_3ds_auth":1,"has_delivery_proof":1,"has_avs_cvv_match":1,"has_ip_device_fingerprint":1,"has_prior_comms":1,"has_signed_receipt":0,"has_usage_logs":0,"days_remaining":10,"days_since_transaction":20,"repeat_dispute_count":0,"transaction_amount_inr":2200.0,"merchant_category":"retail","merchant_current_dispute_ratio":0.004},
    {"reason_code":"mc_4837","network":"mastercard","has_3ds_auth":1,"has_delivery_proof":0,"has_avs_cvv_match":1,"has_ip_device_fingerprint":1,"has_prior_comms":0,"has_signed_receipt":0,"has_usage_logs":1,"days_remaining":12,"days_since_transaction":10,"repeat_dispute_count":0,"transaction_amount_inr":3800.0,"merchant_category":"saas","merchant_current_dispute_ratio":0.003},
    {"reason_code":"rupay_ru01","network":"rupay","has_3ds_auth":1,"has_delivery_proof":1,"has_avs_cvv_match":1,"has_ip_device_fingerprint":1,"has_prior_comms":0,"has_signed_receipt":0,"has_usage_logs":0,"days_remaining":9,"days_since_transaction":12,"repeat_dispute_count":0,"transaction_amount_inr":1800.0,"merchant_category":"ecommerce","merchant_current_dispute_ratio":0.006},
    {"reason_code":"visa_10.4","network":"visa","has_3ds_auth":1,"has_delivery_proof":1,"has_avs_cvv_match":1,"has_ip_device_fingerprint":1,"has_prior_comms":1,"has_signed_receipt":1,"has_usage_logs":0,"days_remaining":7,"days_since_transaction":18,"repeat_dispute_count":0,"transaction_amount_inr":6200.0,"merchant_category":"fintech","merchant_current_dispute_ratio":0.002},
    {"reason_code":"mc_4853","network":"mastercard","has_3ds_auth":1,"has_delivery_proof":1,"has_avs_cvv_match":1,"has_ip_device_fingerprint":1,"has_prior_comms":1,"has_signed_receipt":0,"has_usage_logs":1,"days_remaining":11,"days_since_transaction":8,"repeat_dispute_count":0,"transaction_amount_inr":3100.0,"merchant_category":"saas","merchant_current_dispute_ratio":0.004},
    {"reason_code":"rupay_1062","network":"rupay","has_3ds_auth":1,"has_delivery_proof":1,"has_avs_cvv_match":0,"has_ip_device_fingerprint":1,"has_prior_comms":1,"has_signed_receipt":0,"has_usage_logs":1,"days_remaining":8,"days_since_transaction":22,"repeat_dispute_count":0,"transaction_amount_inr":2700.0,"merchant_category":"retail","merchant_current_dispute_ratio":0.005},
    {"reason_code":"visa_13.3","network":"visa","has_3ds_auth":1,"has_delivery_proof":1,"has_avs_cvv_match":1,"has_ip_device_fingerprint":0,"has_prior_comms":1,"has_signed_receipt":1,"has_usage_logs":0,"days_remaining":6,"days_since_transaction":25,"repeat_dispute_count":0,"transaction_amount_inr":4900.0,"merchant_category":"ecommerce","merchant_current_dispute_ratio":0.003},
    {"reason_code":"mc_4853","network":"mastercard","has_3ds_auth":0,"has_delivery_proof":1,"has_avs_cvv_match":1,"has_ip_device_fingerprint":1,"has_prior_comms":1,"has_signed_receipt":1,"has_usage_logs":1,"days_remaining":13,"days_since_transaction":9,"repeat_dispute_count":0,"transaction_amount_inr":7800.0,"merchant_category":"travel","merchant_current_dispute_ratio":0.007},
    {"reason_code":"rupay_ru02","network":"rupay","has_3ds_auth":1,"has_delivery_proof":1,"has_avs_cvv_match":1,"has_ip_device_fingerprint":1,"has_prior_comms":0,"has_signed_receipt":0,"has_usage_logs":0,"days_remaining":10,"days_since_transaction":14,"repeat_dispute_count":0,"transaction_amount_inr":1500.0,"merchant_category":"ecommerce","merchant_current_dispute_ratio":0.005},

    # --- MODERATE (one_tap_approval) ---
    {"reason_code":"visa_10.4","network":"visa","has_3ds_auth":1,"has_delivery_proof":0,"has_avs_cvv_match":1,"has_ip_device_fingerprint":1,"has_prior_comms":0,"has_signed_receipt":0,"has_usage_logs":0,"days_remaining":8,"days_since_transaction":20,"repeat_dispute_count":1,"transaction_amount_inr":9500.0,"merchant_category":"ecommerce","merchant_current_dispute_ratio":0.009},
    {"reason_code":"mc_4837","network":"mastercard","has_3ds_auth":0,"has_delivery_proof":1,"has_avs_cvv_match":1,"has_ip_device_fingerprint":0,"has_prior_comms":1,"has_signed_receipt":0,"has_usage_logs":0,"days_remaining":6,"days_since_transaction":18,"repeat_dispute_count":1,"transaction_amount_inr":12000.0,"merchant_category":"retail","merchant_current_dispute_ratio":0.008},
    {"reason_code":"rupay_1064","network":"rupay","has_3ds_auth":1,"has_delivery_proof":0,"has_avs_cvv_match":1,"has_ip_device_fingerprint":1,"has_prior_comms":0,"has_signed_receipt":0,"has_usage_logs":1,"days_remaining":7,"days_since_transaction":16,"repeat_dispute_count":1,"transaction_amount_inr":5500.0,"merchant_category":"saas","merchant_current_dispute_ratio":0.010},
    {"reason_code":"visa_13.1","network":"visa","has_3ds_auth":1,"has_delivery_proof":1,"has_avs_cvv_match":0,"has_ip_device_fingerprint":0,"has_prior_comms":0,"has_signed_receipt":0,"has_usage_logs":0,"days_remaining":9,"days_since_transaction":22,"repeat_dispute_count":0,"transaction_amount_inr":8200.0,"merchant_category":"travel","merchant_current_dispute_ratio":0.007},
    {"reason_code":"mc_4853","network":"mastercard","has_3ds_auth":0,"has_delivery_proof":0,"has_avs_cvv_match":1,"has_ip_device_fingerprint":1,"has_prior_comms":1,"has_signed_receipt":0,"has_usage_logs":0,"days_remaining":5,"days_since_transaction":30,"repeat_dispute_count":0,"transaction_amount_inr":6800.0,"merchant_category":"fintech","merchant_current_dispute_ratio":0.008},
    {"reason_code":"rupay_ru01","network":"rupay","has_3ds_auth":0,"has_delivery_proof":1,"has_avs_cvv_match":0,"has_ip_device_fingerprint":1,"has_prior_comms":0,"has_signed_receipt":1,"has_usage_logs":0,"days_remaining":11,"days_since_transaction":13,"repeat_dispute_count":1,"transaction_amount_inr":4200.0,"merchant_category":"ecommerce","merchant_current_dispute_ratio":0.009},
    {"reason_code":"visa_13.3","network":"visa","has_3ds_auth":1,"has_delivery_proof":0,"has_avs_cvv_match":1,"has_ip_device_fingerprint":0,"has_prior_comms":1,"has_signed_receipt":0,"has_usage_logs":0,"days_remaining":8,"days_since_transaction":19,"repeat_dispute_count":0,"transaction_amount_inr":11500.0,"merchant_category":"retail","merchant_current_dispute_ratio":0.006},
    {"reason_code":"mc_4837","network":"mastercard","has_3ds_auth":1,"has_delivery_proof":0,"has_avs_cvv_match":0,"has_ip_device_fingerprint":1,"has_prior_comms":0,"has_signed_receipt":0,"has_usage_logs":1,"days_remaining":6,"days_since_transaction":25,"repeat_dispute_count":1,"transaction_amount_inr":7500.0,"merchant_category":"saas","merchant_current_dispute_ratio":0.011},
    {"reason_code":"rupay_1065","network":"rupay","has_3ds_auth":1,"has_delivery_proof":0,"has_avs_cvv_match":1,"has_ip_device_fingerprint":0,"has_prior_comms":1,"has_signed_receipt":0,"has_usage_logs":0,"days_remaining":4,"days_since_transaction":28,"repeat_dispute_count":0,"transaction_amount_inr":3900.0,"merchant_current_dispute_ratio":0.008,"merchant_category":"ecommerce"},
    {"reason_code":"visa_10.4","network":"visa","has_3ds_auth":0,"has_delivery_proof":1,"has_avs_cvv_match":1,"has_ip_device_fingerprint":1,"has_prior_comms":0,"has_signed_receipt":0,"has_usage_logs":0,"days_remaining":7,"days_since_transaction":21,"repeat_dispute_count":1,"transaction_amount_inr":5100.0,"merchant_category":"fintech","merchant_current_dispute_ratio":0.009},

    # --- DEFLECT (fatal, no evidence, or VAMP breach) ---
    {"reason_code":"mc_4808","network":"mastercard","has_3ds_auth":0,"has_delivery_proof":0,"has_avs_cvv_match":0,"has_ip_device_fingerprint":0,"has_prior_comms":0,"has_signed_receipt":0,"has_usage_logs":0,"days_remaining":8,"days_since_transaction":15,"repeat_dispute_count":0,"transaction_amount_inr":5000.0,"merchant_category":"ecommerce","merchant_current_dispute_ratio":0.010},
    {"reason_code":"visa_12.6","network":"visa","has_3ds_auth":0,"has_delivery_proof":0,"has_avs_cvv_match":0,"has_ip_device_fingerprint":0,"has_prior_comms":0,"has_signed_receipt":0,"has_usage_logs":0,"days_remaining":7,"days_since_transaction":12,"repeat_dispute_count":0,"transaction_amount_inr":3200.0,"merchant_category":"retail","merchant_current_dispute_ratio":0.008},
    {"reason_code":"visa_10.4","network":"visa","has_3ds_auth":0,"has_delivery_proof":0,"has_avs_cvv_match":0,"has_ip_device_fingerprint":0,"has_prior_comms":0,"has_signed_receipt":0,"has_usage_logs":0,"days_remaining":5,"days_since_transaction":40,"repeat_dispute_count":3,"transaction_amount_inr":2100.0,"merchant_category":"ecommerce","merchant_current_dispute_ratio":0.016},
    {"reason_code":"mc_4853","network":"mastercard","has_3ds_auth":0,"has_delivery_proof":0,"has_avs_cvv_match":0,"has_ip_device_fingerprint":0,"has_prior_comms":0,"has_signed_receipt":0,"has_usage_logs":0,"days_remaining":3,"days_since_transaction":35,"repeat_dispute_count":2,"transaction_amount_inr":4400.0,"merchant_category":"travel","merchant_current_dispute_ratio":0.015},
    {"reason_code":"rupay_ru03","network":"rupay","has_3ds_auth":0,"has_delivery_proof":0,"has_avs_cvv_match":0,"has_ip_device_fingerprint":0,"has_prior_comms":0,"has_signed_receipt":0,"has_usage_logs":0,"days_remaining":1,"days_since_transaction":28,"repeat_dispute_count":1,"transaction_amount_inr":1800.0,"merchant_category":"ecommerce","merchant_current_dispute_ratio":0.013},
    {"reason_code":"visa_10.4","network":"visa","has_3ds_auth":0,"has_delivery_proof":0,"has_avs_cvv_match":0,"has_ip_device_fingerprint":0,"has_prior_comms":0,"has_signed_receipt":0,"has_usage_logs":0,"days_remaining":2,"days_since_transaction":30,"repeat_dispute_count":4,"transaction_amount_inr":9800.0,"merchant_category":"saas","merchant_current_dispute_ratio":0.014},
    {"reason_code":"mc_4808","network":"mastercard","has_3ds_auth":1,"has_delivery_proof":1,"has_avs_cvv_match":1,"has_ip_device_fingerprint":1,"has_prior_comms":0,"has_signed_receipt":0,"has_usage_logs":0,"days_remaining":10,"days_since_transaction":14,"repeat_dispute_count":0,"transaction_amount_inr":6500.0,"merchant_category":"fintech","merchant_current_dispute_ratio":0.006},
    {"reason_code":"rupay_1085","network":"rupay","has_3ds_auth":0,"has_delivery_proof":0,"has_avs_cvv_match":0,"has_ip_device_fingerprint":0,"has_prior_comms":0,"has_signed_receipt":0,"has_usage_logs":0,"days_remaining":8,"days_since_transaction":22,"repeat_dispute_count":0,"transaction_amount_inr":3300.0,"merchant_category":"retail","merchant_current_dispute_ratio":0.017},
    {"reason_code":"visa_13.1","network":"visa","has_3ds_auth":0,"has_delivery_proof":0,"has_avs_cvv_match":0,"has_ip_device_fingerprint":0,"has_prior_comms":0,"has_signed_receipt":0,"has_usage_logs":0,"days_remaining":6,"days_since_transaction":45,"repeat_dispute_count":5,"transaction_amount_inr":2900.0,"merchant_category":"ecommerce","merchant_current_dispute_ratio":0.016},
    {"reason_code":"mc_4831","network":"mastercard","has_3ds_auth":0,"has_delivery_proof":0,"has_avs_cvv_match":0,"has_ip_device_fingerprint":0,"has_prior_comms":0,"has_signed_receipt":0,"has_usage_logs":0,"days_remaining":9,"days_since_transaction":20,"repeat_dispute_count":0,"transaction_amount_inr":4700.0,"merchant_category":"travel","merchant_current_dispute_ratio":0.009},

    # --- ESCALATE TO SPECIALIST (high value) ---
    {"reason_code":"visa_10.4","network":"visa","has_3ds_auth":1,"has_delivery_proof":1,"has_avs_cvv_match":1,"has_ip_device_fingerprint":1,"has_prior_comms":1,"has_signed_receipt":1,"has_usage_logs":0,"days_remaining":5,"days_since_transaction":10,"repeat_dispute_count":0,"transaction_amount_inr":150000.0,"merchant_category":"fintech","merchant_current_dispute_ratio":0.003},
    {"reason_code":"mc_4837","network":"mastercard","has_3ds_auth":1,"has_delivery_proof":1,"has_avs_cvv_match":1,"has_ip_device_fingerprint":1,"has_prior_comms":0,"has_signed_receipt":1,"has_usage_logs":1,"days_remaining":3,"days_since_transaction":8,"repeat_dispute_count":0,"transaction_amount_inr":120000.0,"merchant_category":"saas","merchant_current_dispute_ratio":0.004},
    {"reason_code":"visa_13.3","network":"visa","has_3ds_auth":1,"has_delivery_proof":1,"has_avs_cvv_match":1,"has_ip_device_fingerprint":0,"has_prior_comms":1,"has_signed_receipt":1,"has_usage_logs":0,"days_remaining":4,"days_since_transaction":12,"repeat_dispute_count":3,"transaction_amount_inr":200000.0,"merchant_category":"travel","merchant_current_dispute_ratio":0.005},
    {"reason_code":"rupay_ru01","network":"rupay","has_3ds_auth":1,"has_delivery_proof":1,"has_avs_cvv_match":1,"has_ip_device_fingerprint":1,"has_prior_comms":1,"has_signed_receipt":0,"has_usage_logs":1,"days_remaining":2,"days_since_transaction":15,"repeat_dispute_count":0,"transaction_amount_inr":175000.0,"merchant_category":"ecommerce","merchant_current_dispute_ratio":0.006},
    {"reason_code":"mc_4853","network":"mastercard","has_3ds_auth":0,"has_delivery_proof":1,"has_avs_cvv_match":1,"has_ip_device_fingerprint":1,"has_prior_comms":1,"has_signed_receipt":1,"has_usage_logs":1,"days_remaining":6,"days_since_transaction":9,"repeat_dispute_count":4,"transaction_amount_inr":110000.0,"merchant_category":"fintech","merchant_current_dispute_ratio":0.004},

    # --- MIXED (remaining to reach 50) ---
    {"reason_code":"visa_10.4","network":"visa","has_3ds_auth":1,"has_delivery_proof":1,"has_avs_cvv_match":0,"has_ip_device_fingerprint":1,"has_prior_comms":0,"has_signed_receipt":0,"has_usage_logs":1,"days_remaining":9,"days_since_transaction":11,"repeat_dispute_count":0,"transaction_amount_inr":3400.0,"merchant_category":"saas","merchant_current_dispute_ratio":0.006},
    {"reason_code":"mc_4837","network":"mastercard","has_3ds_auth":1,"has_delivery_proof":0,"has_avs_cvv_match":1,"has_ip_device_fingerprint":1,"has_prior_comms":1,"has_signed_receipt":0,"has_usage_logs":0,"days_remaining":7,"days_since_transaction":24,"repeat_dispute_count":0,"transaction_amount_inr":5200.0,"merchant_category":"retail","merchant_current_dispute_ratio":0.005},
    {"reason_code":"rupay_1062","network":"rupay","has_3ds_auth":0,"has_delivery_proof":1,"has_avs_cvv_match":1,"has_ip_device_fingerprint":0,"has_prior_comms":0,"has_signed_receipt":0,"has_usage_logs":0,"days_remaining":12,"days_since_transaction":16,"repeat_dispute_count":0,"transaction_amount_inr":2100.0,"merchant_category":"ecommerce","merchant_current_dispute_ratio":0.007},
    {"reason_code":"visa_13.1","network":"visa","has_3ds_auth":0,"has_delivery_proof":1,"has_avs_cvv_match":1,"has_ip_device_fingerprint":1,"has_prior_comms":1,"has_signed_receipt":0,"has_usage_logs":0,"days_remaining":8,"days_since_transaction":20,"repeat_dispute_count":1,"transaction_amount_inr":4700.0,"merchant_category":"travel","merchant_current_dispute_ratio":0.008},
    {"reason_code":"mc_4853","network":"mastercard","has_3ds_auth":1,"has_delivery_proof":1,"has_avs_cvv_match":0,"has_ip_device_fingerprint":0,"has_prior_comms":0,"has_signed_receipt":1,"has_usage_logs":0,"days_remaining":10,"days_since_transaction":18,"repeat_dispute_count":0,"transaction_amount_inr":6100.0,"merchant_category":"fintech","merchant_current_dispute_ratio":0.004},
    {"reason_code":"rupay_ru02","network":"rupay","has_3ds_auth":1,"has_delivery_proof":0,"has_avs_cvv_match":1,"has_ip_device_fingerprint":1,"has_prior_comms":0,"has_signed_receipt":0,"has_usage_logs":0,"days_remaining":5,"days_since_transaction":22,"repeat_dispute_count":0,"transaction_amount_inr":1900.0,"merchant_category":"ecommerce","merchant_current_dispute_ratio":0.006},
    {"reason_code":"visa_10.4","network":"visa","has_3ds_auth":0,"has_delivery_proof":0,"has_avs_cvv_match":1,"has_ip_device_fingerprint":1,"has_prior_comms":0,"has_signed_receipt":0,"has_usage_logs":1,"days_remaining":9,"days_since_transaction":14,"repeat_dispute_count":2,"transaction_amount_inr":4300.0,"merchant_category":"saas","merchant_current_dispute_ratio":0.012},
    {"reason_code":"mc_4837","network":"mastercard","has_3ds_auth":1,"has_delivery_proof":1,"has_avs_cvv_match":1,"has_ip_device_fingerprint":0,"has_prior_comms":0,"has_signed_receipt":0,"has_usage_logs":0,"days_remaining":6,"days_since_transaction":28,"repeat_dispute_count":0,"transaction_amount_inr":3600.0,"merchant_category":"retail","merchant_current_dispute_ratio":0.006},
    {"reason_code":"rupay_1065","network":"rupay","has_3ds_auth":1,"has_delivery_proof":1,"has_avs_cvv_match":1,"has_ip_device_fingerprint":1,"has_prior_comms":1,"has_signed_receipt":0,"has_usage_logs":0,"days_remaining":8,"days_since_transaction":10,"repeat_dispute_count":0,"transaction_amount_inr":2800.0,"merchant_category":"ecommerce","merchant_current_dispute_ratio":0.005},
    {"reason_code":"visa_13.3","network":"visa","has_3ds_auth":0,"has_delivery_proof":0,"has_avs_cvv_match":1,"has_ip_device_fingerprint":0,"has_prior_comms":1,"has_signed_receipt":0,"has_usage_logs":0,"days_remaining":4,"days_since_transaction":35,"repeat_dispute_count":1,"transaction_amount_inr":7200.0,"merchant_category":"travel","merchant_current_dispute_ratio":0.013},
    {"reason_code":"mc_4853","network":"mastercard","has_3ds_auth":1,"has_delivery_proof":0,"has_avs_cvv_match":0,"has_ip_device_fingerprint":1,"has_prior_comms":0,"has_signed_receipt":0,"has_usage_logs":1,"days_remaining":7,"days_since_transaction":19,"repeat_dispute_count":0,"transaction_amount_inr":5800.0,"merchant_category":"saas","merchant_current_dispute_ratio":0.007},
    {"reason_code":"rupay_ru01","network":"rupay","has_3ds_auth":0,"has_delivery_proof":1,"has_avs_cvv_match":1,"has_ip_device_fingerprint":1,"has_prior_comms":1,"has_signed_receipt":0,"has_usage_logs":0,"days_remaining":11,"days_since_transaction":12,"repeat_dispute_count":0,"transaction_amount_inr":3100.0,"merchant_category":"ecommerce","merchant_current_dispute_ratio":0.006},
]
