"""
Step 1: Synthetic Chargeback Dispute Dataset Generator
=======================================================
AUTO-GENERATED by ingest_hf_reason_codes.py
Dataset source: MattMMarketing/chargeback-reason-codes (HuggingFace CC BY 4.0)

Base win rates are derived from the real winnability_label field:
  "Highly winnable"              → 0.80
  "Winnable with strong evidence"→ 0.62
  "Often winnable"               → 0.50

Generates 5000 labeled chargeback dispute records across Visa, MC, Amex, Discover.
"""

import numpy as np
import pandas as pd
import math
import random
import os

RANDOM_SEED = 42
np.random.seed(RANDOM_SEED)
random.seed(RANDOM_SEED)

N_SAMPLES = 5000

REASON_CODES = {
    "visa_10.4": {"network": "visa", "base": 0.8, "is_fraud": True, "required": ["has_avs_cvv_match", "has_delivery_proof", "has_ip_device_fingerprint", "has_signed_receipt"]},
    "visa_10.3": {"network": "visa", "base": 0.62, "is_fraud": True, "required": ["has_signed_receipt"]},
    "visa_10.1": {"network": "visa", "base": 0.8, "is_fraud": True, "required": []},
    "visa_10.2": {"network": "visa", "base": 0.8, "is_fraud": True, "required": []},
    "visa_13.1": {"network": "visa", "base": 0.62, "is_fraud": False, "required": ["has_delivery_proof", "has_signed_receipt", "has_usage_logs"]},
    "visa_13.2": {"network": "visa", "base": 0.62, "is_fraud": False, "required": ["has_prior_comms", "has_usage_logs"]},
    "visa_13.3": {"network": "visa", "base": 0.62, "is_fraud": False, "required": ["has_prior_comms"]},
    "visa_13.5": {"network": "visa", "base": 0.62, "is_fraud": False, "required": []},
    "visa_13.6": {"network": "visa", "base": 0.5, "is_fraud": False, "required": ["has_prior_comms"]},
    "visa_13.7": {"network": "visa", "base": 0.62, "is_fraud": False, "required": []},
    "visa_12.5": {"network": "visa", "base": 0.62, "is_fraud": False, "required": ["has_signed_receipt"]},
    "visa_12.6.1": {"network": "visa", "base": 0.5, "is_fraud": False, "required": []},
    "visa_11.3": {"network": "visa", "base": 0.62, "is_fraud": False, "required": []},
    "visa_11.1": {"network": "visa", "base": 0.62, "is_fraud": False, "required": []},
    "visa_11.2": {"network": "visa", "base": 0.62, "is_fraud": False, "required": []},
    "visa_12.1": {"network": "visa", "base": 0.62, "is_fraud": False, "required": []},
    "visa_10.5": {"network": "visa", "base": 0.62, "is_fraud": True, "required": ["has_avs_cvv_match", "has_delivery_proof", "has_ip_device_fingerprint"]},
    "visa_13.4": {"network": "visa", "base": 0.62, "is_fraud": True, "required": []},
    "visa_13.8": {"network": "visa", "base": 0.62, "is_fraud": False, "required": ["has_prior_comms"]},
    "visa_13.9": {"network": "visa", "base": 0.62, "is_fraud": False, "required": []},
    "mc_4837": {"network": "mc", "base": 0.8, "is_fraud": True, "required": ["has_avs_cvv_match", "has_delivery_proof", "has_ip_device_fingerprint"]},
    "mc_4853": {"network": "mc", "base": 0.62, "is_fraud": False, "required": ["has_delivery_proof", "has_prior_comms"]},
    "mc_4855": {"network": "mc", "base": 0.62, "is_fraud": False, "required": ["has_delivery_proof", "has_signed_receipt", "has_usage_logs"]},
    "mc_4834": {"network": "mc", "base": 0.5, "is_fraud": False, "required": []},
    "mc_4841": {"network": "mc", "base": 0.62, "is_fraud": False, "required": ["has_prior_comms", "has_usage_logs"]},
    "mc_4808": {"network": "mc", "base": 0.62, "is_fraud": False, "required": []},
    "mc_4863": {"network": "mc", "base": 0.8, "is_fraud": True, "required": ["has_signed_receipt"]},
    "mc_4870": {"network": "mc", "base": 0.8, "is_fraud": True, "required": []},
    "mc_4871": {"network": "mc", "base": 0.62, "is_fraud": True, "required": []},
    "mc_4812": {"network": "mc", "base": 0.62, "is_fraud": False, "required": []},
    "mc_4850": {"network": "mc", "base": 0.62, "is_fraud": False, "required": []},
    "amex_F29": {"network": "amex", "base": 0.8, "is_fraud": True, "required": ["has_avs_cvv_match", "has_delivery_proof", "has_ip_device_fingerprint"]},
    "amex_C08": {"network": "amex", "base": 0.62, "is_fraud": False, "required": ["has_delivery_proof", "has_usage_logs"]},
    "amex_C31": {"network": "amex", "base": 0.62, "is_fraud": False, "required": []},
    "amex_C02": {"network": "amex", "base": 0.5, "is_fraud": False, "required": []},
    "amex_C04": {"network": "amex", "base": 0.62, "is_fraud": False, "required": ["has_prior_comms"]},
    "amex_C05": {"network": "amex", "base": 0.62, "is_fraud": False, "required": ["has_prior_comms", "has_usage_logs"]},
    "amex_P05": {"network": "amex", "base": 0.62, "is_fraud": False, "required": ["has_signed_receipt"]},
    "amex_P08": {"network": "amex", "base": 0.5, "is_fraud": False, "required": []},
    "amex_F10": {"network": "amex", "base": 0.62, "is_fraud": True, "required": ["has_signed_receipt"]},
    "amex_F14": {"network": "amex", "base": 0.62, "is_fraud": False, "required": ["has_signed_receipt"]},
    "amex_F24": {"network": "amex", "base": 0.8, "is_fraud": True, "required": ["has_avs_cvv_match", "has_delivery_proof", "has_ip_device_fingerprint"]},
    "amex_F30": {"network": "amex", "base": 0.62, "is_fraud": True, "required": []},
    "amex_F31": {"network": "amex", "base": 0.62, "is_fraud": True, "required": []},
    "amex_A01": {"network": "amex", "base": 0.62, "is_fraud": False, "required": []},
    "amex_A02": {"network": "amex", "base": 0.62, "is_fraud": False, "required": []},
    "amex_A08": {"network": "amex", "base": 0.62, "is_fraud": False, "required": []},
    "amex_C14": {"network": "amex", "base": 0.5, "is_fraud": False, "required": []},
    "amex_C18": {"network": "amex", "base": 0.62, "is_fraud": False, "required": []},
    "amex_C28": {"network": "amex", "base": 0.62, "is_fraud": False, "required": ["has_usage_logs"]},
    "amex_M10": {"network": "amex", "base": 0.62, "is_fraud": False, "required": []},
    "amex_M49": {"network": "amex", "base": 0.62, "is_fraud": False, "required": ["has_avs_cvv_match"]},
    "amex_R03": {"network": "amex", "base": 0.62, "is_fraud": False, "required": ["has_delivery_proof", "has_signed_receipt"]},
    "amex_R13": {"network": "amex", "base": 0.62, "is_fraud": False, "required": []},
    "disc_UD": {"network": "disc", "base": 0.8, "is_fraud": True, "required": ["has_avs_cvv_match", "has_delivery_proof"]},
    "disc_RG": {"network": "disc", "base": 0.62, "is_fraud": False, "required": ["has_delivery_proof", "has_usage_logs"]},
    "disc_RM": {"network": "disc", "base": 0.62, "is_fraud": False, "required": []},
    "disc_CD": {"network": "disc", "base": 0.5, "is_fraud": False, "required": []},
    "disc_DP": {"network": "disc", "base": 0.5, "is_fraud": False, "required": []},
    "disc_AP": {"network": "disc", "base": 0.62, "is_fraud": True, "required": ["has_prior_comms", "has_usage_logs"]},
    "disc_AA": {"network": "disc", "base": 0.8, "is_fraud": False, "required": ["has_avs_cvv_match", "has_delivery_proof"]},
    "disc_nan": {"network": "disc", "base": 0.62, "is_fraud": False, "required": []},
    "disc_IC": {"network": "disc", "base": 0.62, "is_fraud": False, "required": ["has_signed_receipt"]},
    "disc_UA": {"network": "disc", "base": 0.8, "is_fraud": True, "required": ["has_avs_cvv_match", "has_delivery_proof", "has_ip_device_fingerprint", "has_signed_receipt"]},
    "rupay_ru01": {"network": "rupay", "base": 0.8, "is_fraud": True, "required": ["has_avs_cvv_match", "has_delivery_proof", "has_ip_device_fingerprint"]},
    "rupay_ru02": {"network": "rupay", "base": 0.62, "is_fraud": False, "required": ["has_delivery_proof", "has_signed_receipt"]},
    "rupay_1062": {"network": "rupay", "base": 0.62, "is_fraud": False, "required": ["has_prior_comms", "has_delivery_proof"]},
    "rupay_1065": {"network": "rupay", "base": 0.5, "is_fraud": False, "required": []},
    "rupay_1085": {"network": "rupay", "base": 0.62, "is_fraud": False, "required": ["has_prior_comms"]},
}

FRAUD_CODES = {k for k, v in REASON_CODES.items() if v["is_fraud"]}

VISA_CODES  = [k for k, v in REASON_CODES.items() if v["network"] == "visa"]
MC_CODES    = [k for k, v in REASON_CODES.items() if v["network"] == "mc"]
AMEX_CODES  = [k for k, v in REASON_CODES.items() if v["network"] == "amex"]
DISC_CODES  = [k for k, v in REASON_CODES.items() if v["network"] == "disc"]
RUPAY_CODES = [k for k, v in REASON_CODES.items() if v["network"] == "rupay"]

MERCHANT_CATEGORIES = ["ecommerce", "saas", "travel", "fintech", "retail", "healthcare"]


def sample_reason_code() -> str:
    # Adding RuPay with 25% distribution to simulate Indian domestic market reality
    network = np.random.choice(["visa", "mc", "rupay", "amex", "disc"], p=[0.35, 0.25, 0.25, 0.10, 0.05])
    if   network == "visa":  return random.choice(VISA_CODES)
    elif network == "mc":    return random.choice(MC_CODES)
    elif network == "rupay": return random.choice(RUPAY_CODES)
    elif network == "amex":  return random.choice(AMEX_CODES)
    else:                    return random.choice(DISC_CODES)


def compute_evidence_completeness(row: dict, required: list) -> int:
    if not required:
        return 2
    present = sum(1 for r in required if row.get(r, 0) == 1)
    if present == 0:               return 0
    elif present < len(required):  return 1
    else:                          return 2


def compute_label(row: dict) -> int:
    code = row["reason_code"]
    meta = REASON_CODES[code]
    base = meta["base"]

    # Start score from the real HF base rate
    S = base * 5.0   # scale into sigmoid space so 0.80 → S~4, 0.50 → S~2.5

    # Evidence completeness bonus/penalty
    S += (row["evidence_completeness_score"] - 1) * 1.5  # 0→-1.5, 1→0, 2→+1.5

    # 3DS liability shift for fraud codes
    if row["has_3ds_auth"] == 1 and code in FRAUD_CODES:
        S += 2.0

    # Strict penalty for mc_4853 (Goods Not Received) if delivery proof is missing
    if code == "mc_4853":
        if row["has_delivery_proof"] == 0:
            S -= 2.5  # Heavy penalty - almost certainly a loss
        else:
            S += 1.0  # Strong boost - very likely a win

    # CE 3.0 full match bonus for Visa 10.4 equivalent codes
    if meta["is_fraud"] and meta["network"] == "visa":
        if row["has_ip_device_fingerprint"] == 1 and row["has_avs_cvv_match"] == 1:
            S += 1.5
        else:
            S -= 1.0

    # Repeat dispute penalty (friendly fraud signal)
    if row["repeat_dispute_count"] >= 2:
        S -= 1.2 * math.sqrt(row["repeat_dispute_count"])

    # Deadline pressure
    if row["days_remaining"] <= 2:
        S -= 1.5
    elif row["days_remaining"] <= 5:
        S -= 0.5

    # Staleness penalty
    if row["days_since_transaction"] > 90:
        S -= 1.0

    # High-value issuer scrutiny
    if row["transaction_amount_inr"] > 100000:
        S -= 0.5

    p_win = 1 / (1 + math.exp(-(S - 2.5)))
    return 1 if random.random() < p_win else 0


def generate_dataset(n: int) -> pd.DataFrame:
    records = []
    for _ in range(n):
        code = sample_reason_code()
        meta = REASON_CODES[code]

        row = {
            "reason_code":               code,
            "network":                   meta["network"],
            "has_3ds_auth":              np.random.binomial(1, 0.65),
            "has_delivery_proof":        np.random.binomial(1, 0.55),
            "has_avs_cvv_match":         np.random.binomial(1, 0.70),
            "has_ip_device_fingerprint": np.random.binomial(1, 0.60),
            "has_prior_comms":           np.random.binomial(1, 0.45),
            "has_signed_receipt":        np.random.binomial(1, 0.30),
            "has_usage_logs":            np.random.binomial(1, 0.40),
            "days_remaining":            np.random.randint(1, 46),
            "days_since_transaction":    np.random.randint(1, 121),
            "repeat_dispute_count":      int(np.random.choice(
                                            [0, 1, 2, 3, 4, 5, 8],
                                            p=[0.55, 0.20, 0.10, 0.07, 0.04, 0.02, 0.02]
                                        )),
            "transaction_amount_inr":    round(np.random.exponential(scale=8000) + 100, 2),
            "merchant_category":         random.choice(MERCHANT_CATEGORIES),
        }

        row["evidence_completeness_score"] = compute_evidence_completeness(row, meta["required"])
        row["outcome"] = compute_label(row)
        records.append(row)

    return pd.DataFrame(records)


if __name__ == "__main__":
    print(f"Generating {N_SAMPLES} synthetic chargeback records...")
    print(f"  Networks covered: Visa, Mastercard, Amex, Discover")
    print(f"  Reason codes:     {len(REASON_CODES)} (sourced from HuggingFace MattMMarketing dataset)")
    df = generate_dataset(N_SAMPLES)

    os.makedirs("data/chargeback", exist_ok=True)
    df.to_csv("data/chargeback/chargeback_raw.csv", index=False)

    print(f"\nDataset saved: data/chargeback/chargeback_raw.csv")
    print(f"Shape: {df.shape}")
    print(f"\nOverall win rate: {df['outcome'].mean():.1%}")
    print(f"\nWin rate by network:")
    print(df.groupby("network")["outcome"].agg(["count", "mean"]).round(3))
    print(f"\nWin rate by reason_code (bottom 5):")
    print(df.groupby("reason_code")["outcome"].mean().sort_values().head(5).round(3))
    print(f"\nWin rate by reason_code (top 5):")
    print(df.groupby("reason_code")["outcome"].mean().sort_values().tail(5).round(3))
